### ISSUE TITLE
tabs : décalage des tab-items

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/pepin#3]
Il y a un décalage entre chaque tab-items, en raison de la bordure de 1px : chacun est décalé de la somme des bordures précédentes. C'est encore plus flagrant en agrandissant la bordure.

Je tente un PR pour corriger ça :)

EDIT : en fait c'est dû au `visibility: hidden` sur les `.tabs-content-item[aria-hidden="true"]`. Modifier en `display: none` corrige le problème mais je ne sais pas si c'est OK pour l'accessibilité. ping @PhilippeVay

**Comment by blupdew** [comment]
Résolu en attendant par `border: 0`. On peut certainement utiliser `display:none`

**Comment by PhilippeVay** [comment]
@raphaelgoetter @blupdew Je n'ai pas de démo sous les yeux mais si un élément est caché avec `[aria-hidden="true]`, tu peux bien lui coller un `display: none` c'est un pléonasme 😉
